---
title: "Main text for vaccination strategy paper"
author: "Forrest Jones"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
  word_document: default 
---

```{r setup, include=FALSE}


library(knitr)

knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE,fig.height = 7,
                      fig.width = 10, eval=FALSE,
                      dev="pdf" )

```





```{r libraries, eval = TRUE}
library(tidyverse)
library(readxl)
library(readstata13)
library(randomForest)
library(cowplot)
library(party)
library(tidybayes)

source("source/final_code/shared/utils.R")
source("source/final_code/shared/utils_vax.R")
source("source/final_code/shared/utils_recon.R")


library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

```


```{r data, eval=TRUE}

source("source/final_code/vax_strategy/R/load-data.R")



```

## Methods

```{r}


```


## Results

### Study population

```{r}

final_wide %>% group_by(cohort)%>%
        summarise(n=n(),
                  individuals = length(unique(id))
                  )

final_wide %>% 
        filter(cohort=="BGD Vaccinee") %>%
        count(day)

```


```{r}

individual_data <-analysisData$netMFI_data$wide_data %>%distinct(status,id,age,day,day_actual,sex,Ogawa)

individual_data %>% distinct(id,day,status) %>% 
                group_by(status) %>%
                summarize(n(),length(unique(id)))

individual_data %>% distinct(id,status,age) %>%
                group_by(status,age<18) %>%
                count() %>% 
                group_by(status) %>%
                mutate(total=sum(n)) %>%
                mutate(prop=scales::percent(n/total))

individual_data %>% distinct(id,status,sex) %>%
                group_by(status,sex) %>%
                count() %>% 
                group_by(status) %>%
                mutate(total=sum(n)) %>%
                mutate(prop=scales::percent(n/total))

individual_data %>% distinct(id,status,Ogawa) %>%
                group_by(status,Ogawa) %>%
                count() %>% 
                group_by(status) %>%
                mutate(total=sum(n)) %>%
                mutate(prop=scales::percent(n/total))

individual_data %>% filter(status=="Vaccinee") %>% 
                filter(age<18) %>%
                distinct(id,day,day_actual) %>%
                mutate(total=length(unique(id))) %>%
                group_by(day) %>%
                summarize(
                          min=min(day_actual),
                          max=max(day_actual),
                          n=n(),
                          total=unique(total)) 

individual_data %>% filter(status=="Vaccinee") %>% 
                filter(age>=18) %>%
                distinct(id,day,day_actual) %>%
                mutate(total=length(unique(id))) %>%
                group_by(day) %>%
                summarize(
                          min=min(day_actual),
                          max=max(day_actual),
                          n=n(),
                          total=unique(total)) %>%
                mutate(prop=scales::percent(n/total,1))



```


### Antibody kinetics of vaccinated volunteers and confirmed cholera cases


```{r}

analysisData$netMFI_data$wide_data %>% filter(status=="Case") %>%
        filter(day==2) %>%
        pull(day_actual) %>% summary()


#understand what proportion had arise in O139 OSP antibodies

analysisData$netMFI_data$long_data %>%
        filter(test_type=="Luminex") %>%
        filter(antigen=="O139BSA") %>%
        filter(status=="Vaccinee") %>%
        group_by(status,age >= 18,isotype,id) %>%
        summarize(baseline= 10^value[day==0],
                  peak= 10^max(value),
                  FC=peak/baseline
                  ) %>%
        group_by(status,isotype) %>%
        summarize(mean(FC>=2) %>% scales::percent(1))

```


### Simulation of serological surveys with questionnaire data on vaccination status

```{r}

sim_df <- read_rds("source/final_code/vax_strategy/generated_rds/simulations/new_sim_df.rds")%>%
        mutate(pretty_coverage=paste(scales::percent(coverage,1),"Coverage")) %>%
        mutate(`Days since second dose`=factor(as.numeric(day)-14))


averages <- sim_df %>% group_by(day,coverage,method) %>% 
        summarize(seroinc=mean(lambda),covestim=mean(gamma))

averages %>% filter(method=="Ignore") %>%
        filter(day==21)%>%
        mutate(seroinc/0.05)

averages %>% filter(method=="Ignore") %>%
        filter(day==90) %>%
        mutate(seroinc-0.05)

averages %>% filter(method!="Ignore") %>%
        filter(coverage==0.75)


```




```{r}
#net mfi data
vax_long_NetMFI <-  vax_data %>%
            mutate(value=`Net MFI`,
                   unit="log10(Net MFI)",
                   #censoring for net MFI
                   censor = ifelse(`Net MFI`==1,
                                   -1L,# lower bound (Net MFI <10)
                                   0L) # exact value
                   ) %>%
            select(studycode,id,value,day,sample,full_test,isotype,
                   subclass,antigen,test_type,unit,censor)


```



```{r}

baseline_RAU<- vax_long_RAU %>% filter(day==0) %>%
                rename(baseline=value) %>%
                select(id,isotype,antigen,baseline)
                
baseline_MFI <- vax_long_NetMFI %>% filter(day==0) %>%
                rename(baseline=value) %>%
                select(id,isotype,antigen,baseline)


vax_long_NetMFI %>% filter(day!=0) %>%
        filter(studycode=="RIKS2") %>%
        left_join(baseline_MFI) %>% 
        group_by(isotype,antigen,day) %>%
        summarize(
                  ranksum_p= wilcox.test(value,baseline,paired=TRUE)$p.value,
                  t.test_p = t.test(value,baseline,paired=TRUE)$p.value
                  ) %>%
        filter(ranksum_p<.05/231) %>% 
        arrange(-day,isotype)


vax_long_RAU %>% filter(day!=0) %>%
        filter(studycode=="RIKS2") %>%
        left_join(baseline_RAU) %>% 
        group_by(isotype,antigen,day) %>%
        summarize(
                  ranksum_p= wilcox.test(value,baseline,paired=TRUE)$p.value,
                  t.test_p = t.test(value,baseline,paired=TRUE)$p.value
                  ) %>%
        ggplot(aes(x=factor(day),y=antigen))+
                geom_tile(aes(fill=t.test_p))+
                facet_wrap(.~isotype)+
                scale_fill_distiller(trans="log10",breaks = c(0.05,0.001))



vax_long_RAU %>% filter(antigen=="OgawaOSPBSA")  %>%
                ggplot(aes(x=day,y=value,col=isotype))+
                geom_line(aes(group=id))+
                geom_smooth(se=FALSE,method="loess",col="black")+
                scale_x_continuous(trans = "sqrt")+
                facet_wrap(.~isotype)



```

### Distinguishing recently infected and vaccinated individuals using serological data


```{r}


multi_class_data%>% distinct(id,sample,status,vaxinf_class,day) %>% 
        group_by(vaxinf_class) %>%
        summarize(individuals=length(unique(id)),
                  samples=n()
        )

multi_class_data%>% distinct(id,sample,status,vaxinf_class,day) %>% 
        group_by(vaxinf_class,status,day) %>%
        summarize(individuals=length(unique(id)),
                  samples=n()
        )

```


### Misclassification of vaccinated individuals as recently infected



```{r}

raw_df <- read_rds(
          paste0("source/final_code/vax_strategy/generated_rds/fpr-estimates/","raw_df.rds")
)
tvfpr_df <- read_rds(
          paste0("source/final_code/vax_strategy/generated_rds/fpr-estimates/","tvfpr_df.rds")
)


raw_df %>% #limit the panels and models to show
                filter(age <18) %>%
                filter(variables=="Reduced Panel IgG") %>%
                mutate(end_window=as.numeric(end_window))%>%
                group_by(day,end_window) %>%
                summarize(n=n(),
                          seropos=sum(spec95_seropos)
                          ) %>%
                mutate(prop=scales::percent(seropos/n))


raw_df %>% #limit the panels and models to show
                filter(age >=18) %>%
                filter(variables=="Reduced Panel IgG") %>%
                mutate(end_window=as.numeric(end_window))%>%
                group_by(day,end_window) %>%
                summarize(n=n(),
                          seropos=sum(spec95_seropos)
                          ) %>%
                mutate(prop=scales::percent(seropos/n))



tvfpr_df%>% 
        #limit the panels and models to show
                filter(age_group=="Adult") %>%
                filter(seropos_type=="spec95_seropos") %>%
                filter(variables=="Reduced Panel IgG") %>%
                group_by(end_window)%>%
                filter(median==max(median))

        
        
        
```




